import { StyleSheet } from 'react-native';
import { colors } from '../../styles/theme';

export const styles = StyleSheet.create({
    modalContainer: {
        flex: 1,
        backgroundColor: colors.background,
    },
    content: {
        flex: 1,
        paddingHorizontal: 25,
        paddingTop: 60,
        paddingBottom: 40,
        justifyContent: 'space-between',
        backgroundColor: 'rgba(255, 255, 255, 0.02)',
    },
    headerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    glassCircle: {
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.glassDark,
        borderWidth: 1,
        borderColor: colors.border,
    },
    albumContainer: {
        width: '100%',
        aspectRatio: 1,
        borderRadius: 30,
        marginTop: 20,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
        backgroundColor: '#111111',
        elevation: 15,
    },
    albumImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    floatingBadge: {
        position: 'absolute',
        top: 20,
        right: 20,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        gap: 6,
    },
    floatingBadgeText: {
        color: colors.accent,
        fontSize: 10,
        fontWeight: 'bold',
        letterSpacing: 1,
    },
    glassPanel: {
        borderRadius: 35,
        padding: 25,
        backgroundColor: colors.glassDark,
        borderWidth: 1,
        borderColor: colors.border,
        marginTop: 30,
        marginBottom: 20,
    },
    metaRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        marginBottom: 25,
    },
    titleText: {
        color: colors.primary,
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 4,
    },
    artistText: {
        color: colors.textMuted,
        fontSize: 16,
        fontWeight: '500',
    },
    progressContainer: {
        width: '100%',
        marginBottom: 25,
    },
    progressBarBg: {
        width: '100%',
        height: 6,
        backgroundColor: colors.progressBg,
        borderRadius: 3,
        position: 'relative',
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: colors.primary,
        borderRadius: 3,
    },
    sliderThumb: {
        position: 'absolute',
        top: -5,
        width: 16,
        height: 16,
        borderRadius: 8,
        backgroundColor: colors.primary,
        marginLeft: -8,
        elevation: 5,
    },
    timeRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 10,
    },
    timeText: {
        color: 'rgba(255, 255, 255, 0.5)',
        fontSize: 12,
        fontWeight: '600',
    },
    controlsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    playCircle: {
        width: 76,
        height: 76,
        borderRadius: 38,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 10,
    },
    footerRow: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        alignItems: 'center',
    },
    footerAction: {
        padding: 15,
    }
});